---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


global_config:
  environment_name: cp4waiops
  cloud_platform: existing-ocp
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Pull Registires
  # --------------------------------------------------------------------------------------------------------------------------------------
  entitled_registry: cp.icr.io
  entitled_registry_user: cp
  catalog_image: icr.io/cpopen/ibm-operator-catalog:latest
  # Create Welcome Cards in CP4WAIOps
  create_cards: true
  # Create App Menu Items in OCP
  create_ocp_items: true
  # Use this Password for all Instances
  # Deployment will not work if these aren't changed
  global_password: CHANGEME
  # Set this value to True to accept all licenses
  accept_all_licenses: False
  # Create Notifications in OCP
  create_ocp_notifications: true
  position_ocp_notifications: BannerTop
  position_final_ocp_notification: BannerTop
  # Key to decrypt Licenses
  # license_token: NONE


openshift:
- name: "mycluster"
  ocp_version: "4.12"
  cluster_name: "mycluster"
  domain_name: example.com
  openshift_storage:
  - storage_name: auto-storage
    storage_type: auto
    # Alternatively use
    #storage_name: ibm-roks-storage
    #storage_type: custom
    #ocp_storage_class_file: ibmc-file-gold-gid
    #ocp_storage_class_block: ibmc-block-gold


cp4waiops:
- project: cp4waiops-addons
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS ARGOCD
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-argoCD
    kind: GitOps
    install: true
    test: 1234

