kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'instana-system:openshift:scc:anyuid'
  namespace: instana-datastores
subjects:
  - kind: ServiceAccount
    name: default
    namespace: instana-datastores
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'instana-system:openshift:scc:privileged'
  namespace: instana-datastores
subjects:
  - kind: ServiceAccount
    name: default
    namespace: instana-datastores
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'instana-system:openshift:scc:hostmount-anyuid'
  namespace: instana-datastores
subjects:
  - kind: ServiceAccount
    name: default
    namespace: instana-datastores
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:hostmount-anyuid'
