#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#         ________  __  ___     ___    ________       
#        /  _/ __ )/  |/  /    /   |  /  _/ __ \____  _____
#        / // __  / /|_/ /    / /| |  / // / / / __ \/ ___/
#      _/ // /_/ / /  / /    / ___ |_/ // /_/ / /_/ (__  ) 
#     /___/_____/_/  /_/    /_/  |_/___/\____/ .___/____/  
#                                           /_/
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ©2023 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"


- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
      name: cp4waiops-notification-main
    spec:
      backgroundColor: '#141a6b'
      color: '#fff'
      location: {{global_config.position_final_ocp_notification | default("BannerTop")}}
      text: 'Starting Installation - Warming Up'
    EOF
  ignore_errors: true



# - name: Show Config
#   debug:
#     var: cp4waiops_cluster
- name: 🟣  Show Config File
  debug:
    var: all_config
    verbosity: 2

- name: 🛠️  Get Global Config
  set_fact: global_config={{ all_config.global_config | default([]) }}
- name: 🟣  Show Global Config
  debug:
    var: global_config
    verbosity: 1

# Get OpenShift cluster associated with this CP4WAIOPS project
- name: Get OpenShift definition to use for {{ current_cp4waiops_cluster.project }}
  include_role: 
    name: get-openshift-cluster
  vars:
    _p_openshift_cluster_name: "{{ current_cp4waiops_cluster.openshift_cluster_name | default('') }}"
- name: 🟣  Show Openshift Config
  debug:
    var: _current_openshift_cluster
    verbosity: 1


- name: 📣 OCP CONSOLE - Create Openshift NOTIFICATION
  shell: |
    OPENSHIFT_ROUTE=$(oc get route -n openshift-console console -o jsonpath={.spec.host})
    INSTALL_POD=$(oc get po -n ibm-aiops-installer -l app=ibm-aiops-installer --no-headers|grep "Running"|grep "1/1"|awk '{print$1}')

    oc delete ConsoleNotification --all
    cat <<EOF | oc apply -f -
    apiVersion: console.openshift.io/v1
    kind: ConsoleNotification
    metadata:
        name: ibm-aiops-notification-password
    spec:
        backgroundColor: '#9a0000'
        color: '#fff'
        location: "BannerBottom"
        text: "❌ FATAL ERROR: Please define your own Password for your installation at global_config.global_password (default to be changed is CHANGEME)"
        link:
            href: "https://$OPENSHIFT_ROUTE/k8s/ns/ibm-aiops-installer/configmaps/ibm-aiops-install-configuration/yaml"
            text: Modify your Configuration

    EOF
  ignore_errors: true
  args:
    executable: /bin/bash
  when: all_config.global_config.global_password == "CHANGEME"



# Get default storage classes for current OpenShift cluster
- name: Get OpenShift storage classes to use for {{ current_cp4waiops_cluster.project }} and storage name {{ current_cp4waiops_cluster.openshift_storage_name }}
  include_role: 
    name: get-openshift-storage
  vars:
    _p_openshift_cluster_name: "{{ _current_openshift_cluster.name }}"
    _p_openshift_storage_name: "{{ current_cp4waiops_cluster.openshift_storage_name | default('') }}"

# Loop over all instances
- name: MAIN LOOP   🚀 Deploy Cloud Pak for Watson AIOps Assets - Loop over Instances for {{current_cp4waiops_cluster.project}}
  include_role:
    name: cp4waiops-install-modules-loop
  loop: "{{ current_cp4waiops_cluster.instances}}"
  loop_control:
    loop_var: current_cp4waiops_feature

